site_name: Bases de datos relacionales
site_url: https://bpaterna.github.io/AD_BD_REL/
site_author: Begoña Paterna
theme:
  name: material
  language: es
  palette:
    scheme: default
    primary: red
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.top
    - navigation.sections
    - search.highlight
    - search.suggest
    - toc.integrate
nav:
  - Contenido:
    - 1. Guía de uso: index.md
    - 2. Introducción: introduccion.md
    - 3. Conexión al SGBD: conexiones.md
  - Material adicional:
    - DB Browser: db_browser_sqlite.md
    - DBeaver: dbeaver.md
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
extra_css:
  - stylesheets/extra.css
use_directory_urls: false
plugins:
  - with-pdf:
      output_path: pdf/AD_BD_REL.pdf
      cover: true
      toc_title: "Índice"
